spring.application.name=backend
spring.security.user.name=admin
spring.security.user.password=heslo123
logging.file.name=logs/app.log
settings.file.path=settings.json
logging.level.root=INFO
logging.level.com.currencyapp=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n